default['java']['jdk_version']='7'
default['aem']['adobe_id']='user@email.com'
default['aem']['adobe_password']='yourpassword'
default['aem']['license.customer.name']='Company Name'
default['aem']['license.downloadID']='xx-xx-xx-xx-xx'
